/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VanMenhRouteImport } from './routes/van-menh'
import { Route as TuViRouteImport } from './routes/tu-vi'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NgayTotRouteImport } from './routes/ngay-tot'
import { Route as NapDiemRouteImport } from './routes/nap-diem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LichAmRouteImport } from './routes/lich-am'
import { Route as HoangDaoRouteImport } from './routes/hoang-dao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VanMenhRoute = VanMenhRouteImport.update({
  id: '/van-menh',
  path: '/van-menh',
  getParentRoute: () => rootRouteImport,
} as any)
const TuViRoute = TuViRouteImport.update({
  id: '/tu-vi',
  path: '/tu-vi',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NgayTotRoute = NgayTotRouteImport.update({
  id: '/ngay-tot',
  path: '/ngay-tot',
  getParentRoute: () => rootRouteImport,
} as any)
const NapDiemRoute = NapDiemRouteImport.update({
  id: '/nap-diem',
  path: '/nap-diem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LichAmRoute = LichAmRouteImport.update({
  id: '/lich-am',
  path: '/lich-am',
  getParentRoute: () => rootRouteImport,
} as any)
const HoangDaoRoute = HoangDaoRouteImport.update({
  id: '/hoang-dao',
  path: '/hoang-dao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hoang-dao': typeof HoangDaoRoute
  '/lich-am': typeof LichAmRoute
  '/login': typeof LoginRoute
  '/nap-diem': typeof NapDiemRoute
  '/ngay-tot': typeof NgayTotRoute
  '/signup': typeof SignupRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tu-vi': typeof TuViRoute
  '/van-menh': typeof VanMenhRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hoang-dao': typeof HoangDaoRoute
  '/lich-am': typeof LichAmRoute
  '/login': typeof LoginRoute
  '/nap-diem': typeof NapDiemRoute
  '/ngay-tot': typeof NgayTotRoute
  '/signup': typeof SignupRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tu-vi': typeof TuViRoute
  '/van-menh': typeof VanMenhRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hoang-dao': typeof HoangDaoRoute
  '/lich-am': typeof LichAmRoute
  '/login': typeof LoginRoute
  '/nap-diem': typeof NapDiemRoute
  '/ngay-tot': typeof NgayTotRoute
  '/signup': typeof SignupRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tu-vi': typeof TuViRoute
  '/van-menh': typeof VanMenhRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hoang-dao'
    | '/lich-am'
    | '/login'
    | '/nap-diem'
    | '/ngay-tot'
    | '/signup'
    | '/tai-khoan'
    | '/tu-vi'
    | '/van-menh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/hoang-dao'
    | '/lich-am'
    | '/login'
    | '/nap-diem'
    | '/ngay-tot'
    | '/signup'
    | '/tai-khoan'
    | '/tu-vi'
    | '/van-menh'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hoang-dao'
    | '/lich-am'
    | '/login'
    | '/nap-diem'
    | '/ngay-tot'
    | '/signup'
    | '/tai-khoan'
    | '/tu-vi'
    | '/van-menh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HoangDaoRoute: typeof HoangDaoRoute
  LichAmRoute: typeof LichAmRoute
  LoginRoute: typeof LoginRoute
  NapDiemRoute: typeof NapDiemRoute
  NgayTotRoute: typeof NgayTotRoute
  SignupRoute: typeof SignupRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  TuViRoute: typeof TuViRoute
  VanMenhRoute: typeof VanMenhRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/van-menh': {
      id: '/van-menh'
      path: '/van-menh'
      fullPath: '/van-menh'
      preLoaderRoute: typeof VanMenhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-vi': {
      id: '/tu-vi'
      path: '/tu-vi'
      fullPath: '/tu-vi'
      preLoaderRoute: typeof TuViRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngay-tot': {
      id: '/ngay-tot'
      path: '/ngay-tot'
      fullPath: '/ngay-tot'
      preLoaderRoute: typeof NgayTotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nap-diem': {
      id: '/nap-diem'
      path: '/nap-diem'
      fullPath: '/nap-diem'
      preLoaderRoute: typeof NapDiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-am': {
      id: '/lich-am'
      path: '/lich-am'
      fullPath: '/lich-am'
      preLoaderRoute: typeof LichAmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoang-dao': {
      id: '/hoang-dao'
      path: '/hoang-dao'
      fullPath: '/hoang-dao'
      preLoaderRoute: typeof HoangDaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HoangDaoRoute: HoangDaoRoute,
  LichAmRoute: LichAmRoute,
  LoginRoute: LoginRoute,
  NapDiemRoute: NapDiemRoute,
  NgayTotRoute: NgayTotRoute,
  SignupRoute: SignupRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  TuViRoute: TuViRoute,
  VanMenhRoute: VanMenhRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
